In [1]:
import numpy as np
import pandas as pd 
import seaborn as sb
from sklearn import metrics

In [2]:
dataset = pd.read_csv("housing_price_dataset.csv")

In [3]:
dataset

       SquareFeet  Bedrooms  Bathrooms  YearBuilt        Price Neighborhood
0            2126         4          1       1969  215355.2836        Rural
1            2459         3          2       1980  195014.2216        Rural
2            1860         2          1       1970  306891.0121       Suburb
3            2294         2          1       1996  206786.7872        Urban
4            2130         5          2       2001  272436.2391       Suburb
...           ...       ...        ...        ...          ...          ...
49995        1282         5          3       1975  100080.8659        Rural
49996        2854         2          2       1988  374507.6567       Suburb
49997        2979         5          3       1962  384110.5556       Suburb
49998        2596         5          2       1984  380512.6860        Rural
49999        1572         5          3       2011  221618.5832        Rural

[50000 rows x 6 columns]

In [4]:
#sb.pairplot(dataset, hue="Area")

In [5]:
X = dataset.iloc[ : , : ]
Y = dataset.iloc[ :, 4]
X

       SquareFeet  Bedrooms  Bathrooms  YearBuilt        Price Neighborhood
0            2126         4          1       1969  215355.2836        Rural
1            2459         3          2       1980  195014.2216        Rural
2            1860         2          1       1970  306891.0121       Suburb
3            2294         2          1       1996  206786.7872        Urban
4            2130         5          2       2001  272436.2391       Suburb
...           ...       ...        ...        ...          ...          ...
49995        1282         5          3       1975  100080.8659        Rural
49996        2854         2          2       1988  374507.6567       Suburb
49997        2979         5          3       1962  384110.5556       Suburb
49998        2596         5          2       1984  380512.6860        Rural
49999        1572         5          3       2011  221618.5832        Rural

[50000 rows x 6 columns]

In [6]:
Area = pd.get_dummies(X["Neighborhood"])
Area

       Rural  Suburb  Urban
0       True   False  False
1       True   False  False
2      False    True  False
3      False   False   True
4      False    True  False
...      ...     ...    ...
49995   True   False  False
49996  False    True  False
49997  False    True  False
49998   True   False  False
49999   True   False  False

[50000 rows x 3 columns]

In [7]:
X = X.drop("Neighborhood",axis=1)
X = pd.concat([X, Area],axis=1)
X

,SquareFeet,Bedrooms,Bathrooms,YearBuilt,Price,Rural,Suburb,Urban
0,2126,4,1,1969,215355.2836,True,False,False
1,2459,3,2,1980,195014.2216,True,False,False
2,1860,2,1,1970,306891.0121,False,True,False
3,2294,2,1,1996,206786.7872,False,False,True
4,2130,5,2,2001,272436.2391,False,True,False
...,...,...,...,...,...,...,...,...
49995,1282,5,3,1975,100080.8659,True,False,False
49996,2854,2,2,1988,374507.6567,False,True,False
49997,2979,5,3,1962,384110.5556,False,True,False
49998,2596,5,2,1984,380512.6860,True,False,False
49999,1572,5,3,2011,221618.5832,True,False,False

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=7)

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)
r_square = metrics.r2_score(y_test, predictions)
print (r_square)

from sklearn.svm import SVR
regressor = SVR(kernel="linear")
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)
r_square = metrics.r2_score(y_test, predictions)
print (r_square)


from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor (max_depth=10)
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)
r_square = metrics.r2_score(y_test, predictions)
print (r_square)


from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor ()
regressor.fit(X_train, y_train)
predictions = regressor.predict(X_test)
r_square = metrics.r2_score(y_test, predictions)
print (r_square)

1.0
0.9999999999998883
0.9999965146644346
0.999999718401387